name: Generate Component Definition

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
    paths:
      - "data/**"

  workflow_dispatch:

jobs:
  generate-component-definition:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Run Trestle
        run: trestle task csv-to-oscal-cd -c ./data/csv-to-oscal-cd.config
          
      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update component-definition by Trestle
          delete-branch: true
          title: Update component-definition by Trestle
